version: '3.8'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=product-microservice-db-test

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672 # AMQP port
