version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3333:3333
      - 9229:9229
    tty: true
    volumes:
      - .:/home/node/app
      - ./node_modules/:/home/node/app/node_modules
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db
    networks:
      - product-microservice-network
      - kommshop-broker_rabbitmq-network

  db:
    image: mongo
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=product-microservice-db-test
    networks:
      - product-microservice-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - db
    networks:
      - product-microservice-network

networks:
  product-microservice-network:
    driver: bridge
  kommshop-broker_rabbitmq-network:
    external: true
