POST http://localhost:3333/api/v1/product HTTP/1.1
content-type: application/json

{
    "name": "Women\"s Leather Jacket Bonita",
    "description":"A stylish leather jacket for women.",
    "category": "Clothing",
    "price": 150
}
###
GET http://localhost:3333/api/v1/product/6513525800fa93928f0112f0 HTTP/1.1
content-type: application/json


###
PATCH http://localhost:3333/api/v1/product/6513525800fa93928f0112f0 HTTP/1.1
content-type: application/json

{
    "name": "Women\"s Leather Jacket Bonita",
    "description":"A stylish leather jacket for women.",
    "category":  "Clothing",
    "price": 150
}


###

POST http://localhost:3333/api/v1/categories HTTP/1.1
content-type: application/json

{
    "name": "Kitchen"
}
###

PATCH http://localhost:3333/api/v1/categories/647c2896ffef2acfe4829a86 HTTP/1.1
content-type: application/json

{
    "name": "FurniTure"
}

###

POST http://localhost:3333/api/v1/product/favourite HTTP/1.1
content-type: application/json

{
    "productId": "651b3ca098550bf75b566d96",
    "userId": "b"
}
###

GET http://localhost:3333/api/v1/product?search=c HTTP/1.1
content-type: application/json

###

GET http://localhost:3333/api/v1/product/651b3ca098550bf75b566d96 HTTP/1.1
content-type: application/json


###

GET http://localhost:3333/api/v1/categories?name=c HTTP/1.1
content-type: application/json
###

GET http://localhost:3333/api/v1/categories HTTP/1.1
content-type: application/json
