POST http://localhost:3333/products HTTP/1.1
content-type: application/json

{
    "name": "Women\"s Leather Jacket",
    "description":"A stylish leather jacket for women.",
    "category":  "Clothing",
    "price": 150
}

###

POST http://localhost:3333/categories HTTP/1.1
content-type: application/json

{
    "name": "Kitchen"
}

###

POST http://localhost:3333/products/favourite HTTP/1.1
content-type: application/json

{
    "productId": "651b3ca098550bf75b566d96",
    "userId": "b"
}
###

GET http://localhost:3333/products?cat=&search= HTTP/1.1
content-type: application/json

###

GET http://localhost:3333/products/651b3ca098550bf75b566d96 HTTP/1.1
content-type: application/json


###

GET http://localhost:3333/categories? HTTP/1.1
content-type: application/json
